- hosts: all
  become: true
  tasks:

  - name: update repository index
    package_manager:
      name: "{{ ansible_pkg_mgr }}"
      update_cache: yes

  - name: install apache2 package
    package_manager:
      name: "{{ apache_package }}"
      state: latest



  - name: install apache2 package
    dnf:
      name: httpd
